### PR TITLE
Fix range and accuracy stats of MP weapons

### PR DESCRIPTION
**Pull request by Forgon2100**
This pull request should fix range and accuracy values for MP weapons.

I created a list of all weapons with their "name" and "id" properties:
```
jq '.[] | [.name,.id] | @csv' weapons.json | tr -d '\\\"' \
> weapon_names.csv
```

I sorted all weapons, using https://betaguide.wz2100.net/weapons.php
and http://betaguide.wz2100.net/structure.php. Categories follow:

* AA (exclusive: Hurricane and Whirlwind, inclusive: all AA weapons)
* Bombs
* Cannons (include Cannon Fortress)
* Command Turret
* EMP cannons (include VTOL EMP Missile Launcher)
* Flamers (exclusive: without bombs, inclusive: with incendiary bombs)
* Howitzers
* Lasers (include Laser Satellite Command Post)
* Machineguns (include a pillbox and MG bunkers)
* Missiles (include Missile Fortress)
* Mortars
* Nexus Link Turret
* Rail guns (include Mass Driver)
* Rockets (include Heavy Rocket Bastion)

Files for all these categories were put in a new directory. Inside it,
I filtered new_weapon_ranges.csv (explained [here](https://github.com/Warzone2100/warzone2100/pull/387#issuecomment-502366740)) for each weapon type:

```
for f in *
do
    cut -d , -f 2 $f | grep -f - ../new_weapon_ranges.csv > ${f}_range
done
```

For each type of weapon, I checked for
* identical accuracy values at different ranges
* short or long ranges being more accurate while similar weapons show
  the opposite behavior. For example, cannons are usually more accurate
  at short ranges, and a cannon more accurate at a long range would be
  an exception that should be double-checked.

Weapon categories can be classified based on their most accurate range:

Short range: cannons, EMP cannons, true flamers, machineguns, rail guns
Long range: AA exclusive, howitzers, missiles, mortars, rockets
No difference: bombs, Command Turret, lasers, Nexus Link Turret 

AA weapons follow the convention of their categories: lasers, missiles,
rockets. Thus, the AA Flak Cannon is more accurate at short range.
To be consistent with that, the Stormbringer AA Laser should have its
short range removed.

Executing `awk -F , '$5 >= $4' cannons_range` prints cannons that are
no more accurate at short range than at long range:

```
Cannon4AUTO-VTOL,768,1280,65,65
Cannon4AUTOMk1,768,1280,65,65
CannonSuper,128,1408,80,90
Cyb-Hvywpn-HPV,758,1152,65,65
Laser4-PlasmaCannon,960,1280,65,65
PlasmaHeavy,1920,9984,40,99
```

The HPV cannons are most similar to assault cannons, and should thus
share their short- and long-range accuracy values of 60 and 50.

The Cannon Fortress has a very short minimum range with lower accuracy
compared to its long range. Its range stats are identical to those used
by the Mass Driver, and can stay as they are.

The Plasma Cannon requires the Hyper Velocity Cannon. Therefore, it
should share its accuracy stats.

The "\*Heavy Plasma Launcher\*" PlasmaHeavy is not used in MP stats, but
used in the campaign for "NX-Emp-Plasma-Pit", a plasma cannon bunker.
Its accuracy stats should be identical to those of the Plasma Cannon.
Since the weapon is unused, its absurdly long range can stay what it is.

All lasers have only one range, except the Laser Satellite Command Post.
Since this weapon should be able to strike anywhere on a map, there is
probably no alternative to it being an exception.

The Mass Driver is the only rail gun more accurate at long range than at
short range. Its range stats should be kept as they are, since they are
identical to those used by the Cannon Fortress. 

The Nexus Link Turret should have no minimum range. The Command Turret
has no minimum range either and is the most similar weapon, using the
same weapon animation, long range and perfect accuracy of 100%.

Executing `awk -F , '$5 <= $4' rockets_range` prints rockets that are
no more accurate at long range than at short range:

```
BabaPitRocket,640,960,60,30 
BabaPitRocketAT,640,960,50,30
BabaRocket,640,960,30,20
Rocket-VTOL-Pod,640,1024,50,30
```

BabaPitRocket and BabaRocket should receive the same accuracy stats as
Rocket-Pod, the Mini-Rocket Pod: 40 at short range, 45 at long range.

BabaPitRocketAT should be as accurate as Rocket-LtA-T, the Lancer: 30 at
short range, 60 at long range.

The Rocket-VTOL-Pod should be more accurate than the Mini-Rocket Pod,
similar to other VTOL weapons. Its new accuracy stats are 50 and 60.

The attached ZIP file contains stats generated from maxsupermanhd's
master branch at [commit 3fded455ccae1e0b2cff2023c5ecc5c1c576b9ee](https://github.com/Warzone2100/warzone2100/pull/387/commits/3fded455ccae1e0b2cff2023c5ecc5c1c576b9ee):
* a CSV file listing weapon ranges
* the MP weapons.json file
* a CSV file listing MP weapons with their "name" and "id" properties
* a directory containing categorized weapons, each with
  * a CSV file listing their "name" and "id" properties
  * a CSV file listing their range and accuracy stats

[mp_weapon_ranges_documentation.zip](https://github.com/maxsupermanhd/warzone2100/files/3294094/mp_weapon_ranges_documentation.zip)

### CODE REVIEW

**Comment by maxsupermanhd** [comment]
Let me think about HPV... All other changes seems to be good.

**Comment by maxsupermanhd** [comment]
Questionably changes with HPV weapons. In old 3.1 branch this type not best and yore getting it weaker. Will this cause rockets winning class like guns+bullets in 3.3.0? And it causes HPV become less accurate than medium cannon... (thinking emoji)

**Comment by Forgon2100** [comment]
> Questionably changes with HPV weapons. In old 3.1 branch this type not best and yore getting it weaker. Will this cause rockets winning class like guns+bullets in 3.3.0? And it causes HPV become less accurate than medium cannon... (thinking emoji)

Could you suggest some other stats?

**Comment by maxsupermanhd** [comment]
I think all changes except HPV is good.

**Comment by maxsupermanhd** [comment]
Was partially applied by Vaut's pull request.

**Pull request closed without merging**
